### ISSUE TITLE
./development/node_helper.md line 115 

### ISSUE THREAD

**Issue by istvanfedak** [MichMich/MagicMirror-Documentation#12]
Hi,

I'm new to the MagicMirror community. I was reading the docs and got confused by line 115 in node_helper.md

It stated the following:
"If you want to send a notification to all your modules, use the `sendSocketNotification(notification, payload)`"

Doesn't `sendNotification(notification, payload)` send notifications to all modules and `sendSocketNotification(notification, payload)` send notifications between node_helper.js and your module?

Thanks!

**Comment by MichMich** [comment]
Sorry for the super slow response. I don't check the issues for this repo very often. 
`sendSocketNotification` sends a notification from the helper to all the instances of your module. 

Feel free to send a PR to clear this up.
