### ISSUE TITLE
weathergov Weather Provider Doc Update

### ISSUE THREAD

**Issue by dWoolridge** [MichMich/MagicMirror-Documentation#131]
After a deep-dive into the weathergov.js weather provider script, I believe the documentation needs to be updated...

https://docs.magicmirror.builders/modules/weather.html#configuration-options

Under "Weather.gov options"

weathergov.js no longer uses the weatherEndpoint configuration setting as the docs suggest. This option should be deleted from the documentation.

**Comment by khassel** [comment]
fix already merged so closing this.
