### ISSUE TITLE
Only 2 day's forcast is displayed

### ISSUE THREAD

**Issue by dipanjansikdar** [MichMich/MagicMirror-Documentation#25]
Hi,

I am new to the MagicMirror with limited coding back ground.
My Weather forcat module is showing only 2 day's forcast irrespectve of the value set in 'maxNumberofDays'

The Module was working perfectly before I updated the latest MagicMirror Version.

![WeathFC](https://user-images.githubusercontent.com/51149633/86356687-45c0e680-bc8a-11ea-9c7e-23f88d49e068.jpg)
![WeathFCconfig](https://user-images.githubusercontent.com/51149633/86356925-b962f380-bc8a-11ea-9b17-c1cb9ef4d64a.jpg)

**Comment by dipanjansikdar** [comment]
Also the Current Weather Module is not showing up most of the time. Some times it shows up intermittently.

This issue also came up ufter MagicMirrior update

**Comment by robertybob** [comment]
@dipanjansikdar  solved here  

https://forum.magicmirror.builders/topic/13187/weatherforecast-showing-only-two-days?_=1595801124846

**Comment by rejas** [comment]
So since this seems to be solved and not really a documentation issue could this be closed @dipanjansikdar ?
Or @MichMich ?
