### ISSUE TITLE
Module/Weather/windUnits>>wrong Description

### ISSUE THREAD

**Issue by RTGitter** [MichMich/MagicMirror-Documentation#38]
Hi!

I haven't tried to change It, because i don't know how...:

In the Documentation of the Weather Module in "WindUnits" it seems to be the wrong units declared: Fahrenheit and Celsius... ?

Can anyone fix it? 

Greetings

**Comment by rejas** [comment]
Sorry for the late response @RTGitter but could you take alook and see if it is still wrong?

**Comment by RTGitter** [comment]
Yes, in
"https://docs.magicmirror.builders/modules/weather.html#configuration-options"

there is still the units in 'Wind units' = Kelvin, Fahrenheit and Celsius!
But i can't test if it is in the MIRROR PROGRAMM or only  in the Documentation, because i have the mirror deinstalled...

**Comment by rejas** [comment]
Ah, yes, right... I overlooked that you ment the windunits. Indeed there the documentation doesnt make sense, it should be something like kmh or mps or something

Will try to fix it soonish...

Looking at the code and the default values I am wondering @MichMich : Default for the units is metric, but the default value for windspeed is miles/h so one has to set the useKmh property explicitly to true to get metric values in there. That sounds inconsistent to me, what do you think?

**Comment by RTGitter** [comment]
Sounds good. Then it will be fixed.

**Comment by MichMich** [comment]
Metric FTW! Agree with the proposed change @rejas!
