### ISSUE TITLE
Update installation for hardware specs

### ISSUE THREAD

**Issue by hajimurtaza** [MichMich/MagicMirror-Documentation#50]
Could you provide some details or resources as to what will be required on hardware side to achieve this.
For eg. i had to google a lot to understand that ill need some sort of display, a two way mirror, maybe a window frame and ofcourse a rasberry pie which you already mentioned.

**Comment by MichMich** [comment]
I recommend checking out http://forum.magicmirror.builders. Feel free to send a PR to add more info about this to the docs. 

Closing this issue for now. Feel free to let me know when I need to reopen.
