### ISSUE TITLE
add this picture to docs (possibly in a new section)

### ISSUE THREAD

**Issue by earlman** [MichMich/MagicMirror-Documentation#59]
add this info to docs from forums:

***

In case one wants to know where the various regions are. Missing are the fullscreen_below and fullscreen_above as those cover the whole screen, one under everything else and the other above.

top_bar and bottom_bar are light gray
top_left and bottom_left are red
top_center and bottom_center are blue
top_right and bottom_right are green
upper_third is yellow
middle_center is cyan
lower_third is magenta

All these regions will resize as needed.

![magicmirrorregions](https://user-images.githubusercontent.com/5160959/113356776-75c81380-9308-11eb-913d-94bf4315bb2d.png)

**Comment by earlman** [comment]
I'll work on this at some point

**Comment by MichMich** [comment]
Cool. Feel free to send a PR!

**Comment by MichMich** [comment]
(Sorry for the slow response. I don't check the issues for this repo very often.)
