### ISSUE TITLE
fieldname for ApiKey

### ISSUE THREAD

**Issue by Renevandenbroek** [MichMich/MagicMirror-Documentation#74]
the fielddname for the Api Key is changed and gives problems while migrating from the previous version

**Comment by MichMich** [comment]
Could you give a bit more info? Maybe in de MagicMirror repo (not docs). We might need to built a solution for this if this indeed is a breaking change.

**Comment by Renevandenbroek** [comment]
I feel a blush coming up. I think I did not read the doc properly. Sorry
about that.
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-4989569246805931346_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op zo 20 jun. 2021 om 14:44 schreef Michael Teeuw ***@***.***

**Comment by rejas** [comment]
So this can be closed @Renevandenbroek ?

**Comment by Renevandenbroek** [comment]
Yes.  thank you.

Op vr 30 jul. 2021 15:32 schreef Veeck ***@***.***>:
