### ISSUE TITLE
Problem with manual installation instructions

### ISSUE THREAD

**Issue by mrlowndes** [MichMich/MagicMirror-Documentation#9]
Why do the manual installation instructions direct the user to install the latest version 10.x of node when "npm does not support Node.js v10.15.2"? 

For a noob, trying to follow these instructions in 2020, they are completely unusable and lead to a dead-end

**Comment by MichMich** [comment]
Feel free to send a PR with the correct instructions.

**Comment by rejas** [comment]
Maybe after https://github.com/MichMich/MagicMirror-Documentation/commit/46d3b15e46390e71c57bebc3cd9f225e69c81388#diff-0671d010b3fd78275b320130400289b7a1017cc186389817bc8635926253e9c3 this is a little clearer @mrlowndes  ?

**Comment by MichMich** [comment]
Fixed in the docs.
