### ISSUE TITLE
No full text search in documentation

### ISSUE THREAD

**Issue by khassel** [MichMich/MagicMirror-Documentation#91]
- enter some text beside the magnifying glass symbol
- press `enter`
- nothing happens

**Comment by rejas** [comment]
The search works if you type common words like "installation" and it then shows the suggestions which are clickable.

The default search seems to search only in specific stuff: https://vuepress.vuejs.org/theme/default-theme-config.html#built-in-search  

"Built-in Search only builds index from the title, h2 and h3 headers and tags. If you need full text search, you can use Algolia Search."

Not sure if the site needs that algolia search. How many visitors are there anyway on a daily basis?

**Comment by khassel** [comment]
> The search works if you type common words like "installation" and it then shows the suggestions which are clickable.

o.k., that works.

But full text search would be helpful, with the discussion of windows support how to find such occurencies without?

**Comment by MichMich** [comment]
I've applied for Agolia DocsSearch. I'll update when/if it gets approved.

**Comment by MichMich** [comment]
I've added DocSearch. It's indexed, but it doesn't return any results when I search. If somebody knows where to look let me know, I'll give it another try later this week.

**Comment by rejas** [comment]
Sorry, cant help there. But since I am here, any feedback on the PRs I prepared for the docs? ;-)

**Comment by MichMich** [comment]
Algolia DocSearch should be working now.
